# Generated by Django 6.0.6 on 2026-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_founder',
            field=models.BooleanField(default=False, help_text='The user who originally registered the company. Founders cannot be deactivated, locked, deleted, or demoted from ownership by anyone, including other owners.'),
        ),
    ]
