# Generated by Django 6.0.6 on 2026-07-03 07:54

import django.db.models.deletion
import rbac.core.validators.phone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[rbac.core.validators.phone.validate_phone_number])),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='company.company')),
            ],
            options={
                'ordering': ['company__name'],
            },
        ),
    ]
