# Generated by Django 6.0.6 on 2026-07-03 10:24

import rbac.core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to=rbac.core.utils.files.company_logo_dark_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_light',
            field=models.ImageField(blank=True, null=True, upload_to=rbac.core.utils.files.company_logo_light_upload_path),
        ),
    ]
