# Generated by Django 6.0.6 on 2026-07-18 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 25, 12, 36, 21, 714488, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
